---

- name: Install docker-ce
  apt: 
    name: "docker-ce={{ docker_engine_version }}~ce-0~ubuntu-{{ ansible_distribution_release }}" 
    state: installed

- name: "Install docker + reqs"
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - python-pip

- name: "Install docker-py"
  pip:
    name: docker-py
    state: present
    version: "{{ docker_py_version }}"

# requests 2.12.2 currently latest has issue with pulling images...
# fails with "no host in request URL"
- name: "Install requests version 2.12.1"
  pip:
    name: requests
    state: present
    version: "{{ docker_requests_version }}"
    
- name: Upgrade pyasn version
  pip:
    name: pyasn1
    state: latest

- name: "add {{ ansible_user }} to docker group"
  user:
    name="{{ ansible_user }}"
    groups=docker
    append=yes

- reset_ssh_session:

#- name: Users - Force new connection so user group takes effect
#  local_action: file path="{{ control_persist_path }}" state=absent
