---
- name: Install AUFS storage driver support packages
  become: yes
  apt: name={{ item }} state=present
  with_items: 
    - "linux-image-extra-{{ ansible_kernel }}"
    - "linux-image-extra-virtual"
  tags:
    - "install"
    - "docker"

- name: "Install docker + reqs"
  become: yes
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - docker-engine
    - python-pip
  tags:
    - apt

- name: "Install docker-py"
  become: yes
  pip:
    name: docker-py
    state: present
    version: 1.7.0
  tags:
    - pip

- name: Install docker-engine
  become: yes
  apt: name="docker-engine={{ docker_engine_version }}-0~{{ ansible_distribution_release }}" state=installed
  tags:
    - "install"
    - "docker"

