---
- name: Install AUFS storage driver support packages
  apt: name={{ item }} state=present
  with_items: 
    - "linux-image-extra-{{ ansible_kernel }}"
    - "linux-image-extra-virtual"

- name: "Install docker + reqs"
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - docker-engine
    - python-pip

- name: "Install docker-py"
  pip:
    name: docker-py
    state: present
    version: "{{ docker_py_version }}"

- name: Install docker-engine
  apt: name="docker-engine={{ docker_engine_version }}-0~{{ ansible_distribution_release }}" state=installed

- name: "add {{ ansible_user }} to docker group"
  become: yes
  user:
    name="{{ ansible_user }}"
    groups=docker
    append=yes

- debug: var=ansible_user

- name: Gather Facts
  setup: 

- debug: var=ansible_user

- name: Check Docker is Running
  command: docker ps
  register: result

- name: print docker ps output
  debug: msg="{{ result.stdout }}"
