---

- name: Uninstall older versions
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
    - lxc-docker

- name: Install kernel headers for aufs support
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual

- name: Install Requirements
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: "Add apt key of the latest repo"
  apt_key:
    url: "{{ gpg_key_url }}"

- name: "Add repository"
  apt_repository:
    repo: 'deb {{ docker_repo }} {{ ansible_distribution_release }} stable'
    state: present

- name: "Verify that apt is pulling from the right repository"
  command: apt-cache policy docker-engine

- name: "Update apt cache for new repo to kick in"
  apt:
    update_cache: yes
