---
# tasks file for docker-engine
- include: configure_apt.yml 
  become: yes
  tags:
    - dockeraptconfig
- include: apt_install_docker.yml
  become: yes
  tags:
    - dockerinstall
- include: configure_daemon.yml
    tags: 
    - dockerconfig
